FROM mariadb:10.5

LABEL app="SO Planning DB"
LABEL maintener="Rémi VERCHERE <remi@verchere.fr>"
LABEL major_version="1"
LABEL minor_version="47"

ENV MYSQL_ROOT_PASSWORD password
ENV MYSQL_DATABASE soplanning
ENV MYSQL_USER soplanning
ENV MYSQL_PASSWORD soplanning

COPY ./sql/planning_mysql.sql /docker-entrypoint-initdb.d
